
spring:
  application:
    name: api-gateway-service

server:
  port: 8080

# Manually register with eureka server
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# Enable dynamic routing
management:
  endpoint:
    routes:
      enabled: true